 AI_Titanic/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('titanic.urls')),
    path('admin/', admin.site.urls),
]

 AI_Titanic/titanic/urls.py
from django.urls import path
from . import views

app_name= 'titanic'
urlpatterns = [
    path('', views.Home, name='home'),
    path('result/', views.Result, name='result'),
]

 AI_Titanic/titanic/models.py
from django.db import models
import joblib
import numpy as np
# from sklearn.externals import joblib

def predict(input_data):
    model = joblib.load('./titanic/Classification/titanic.pkl')
    input_data = np.array(input_data)
    answer = model.predict(input_data)
    return answer

 AI_Titanic/titanic/forms.py
from django import forms

class MyForm(forms.Form):
    # text = forms.CharField(label='文字入力', max_length=100, help_text='100characters max')
    # gender = forms.IntegerField(label='数量')
    gender = forms.ChoiceField(choices = (
            (0, '男性'),
            (1, '女性'),
        ),  
        widget=forms.widgets.Select(attrs={
                'class' : 'btn btn-lg btn-block btn-outline-primary',
                'id': 'select1'}),
    )

    grade = forms.ChoiceField(widget = forms.Select(attrs={
        'class': "btn btn-lg btn-block btn-primary",
        'id': 'select2'
    }), 
        choices = ([('1','First-class'), ('2','Second-class'),('3','Third-class'), ]), initial='3')

    fare = forms.IntegerField(
        label='ドル', 
        initial=0,
        min_value=0,
        max_value=2500,
        widget=forms.TextInput(attrs={
                'class' : 'btn btn-lg btn-block btn-outline-primary',
                'id': 'select3'
        }),
    )
        
    # fields.IntegerRangeField(range(0, 2550))

# forms.TextInput(attrs={'class' : 'myfieldclass'}),
# widget はHTMLの属性を与える
"""
def __init__(self, *args, **kwargs):
        super(ProductForm, self).__init__(*args, **kwargs)
        self.fields['description'].widget = TextInput(attrs={
            'id': 'myCustomId',
            'class': 'myCustomClass',
            'name': 'myCustomName',
            'placeholder': 'myCustomPlaceholder'})
"""

 AI_Titanic/titanic/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .forms import MyForm
from . import models

def Home(request):
    form = MyForm()
    # return render(request, 'titanic/index.html')
    return render(request, 'titanic/index.html', {'form': form})

# def Result(request):
#    return render(request, 'titanic/result.html')

# dictionary-type(辞書型)
def Result(request):
    if request.method == 'POST':
        form = MyForm(request.POST)
        if form.is_valid():
            gender = form.cleaned_data['gender']
            grade = form.cleaned_data['grade']
            fare = form.cleaned_data['fare']

            # predict
            answer = models.predict([[gender, grade, fare]])
            if answer == 0:
                answer = "<h1 id='death'>死亡</h1>"
            else:
                answer = "<h1 id='alive'>生存</h1>"
            
            params = {
                'gender': gender,
                'grade': grade,
                'fare': fare,
                'answer': answer,
            }
            return render(request, 'titanic/result.html', params)
    else:
        return redirect('titanic:home')

 AI_Titanic/titanic/templates/titanic/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v4.0.1">
    <title>Pricing example · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/pricing.css' %}" rel="stylesheet">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/custom.css' %}" rel="stylesheet">
    <link href="{% static 'css/result.css' %}" rel="stylesheet" >

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
  </head>
  <body>
    {% block content %}
      
    {% endblock content %}

<!--JavaScript-->
</body>
</html>

 AI_Titanic/titanic/templates/titanic/index.html
{% extends 'titanic/base.html' %}
{% load static %}

{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">AI Titanic判定</h1>
    <p class="lead">RMS Titanic was a British passenger liner operated by the White Star Line 
        that sank in the North Atlantic Ocean in the early morning hours of 15 April 1912, 
        after striking an iceberg during her maiden voyage <br>from Southampton to New York City.</p>
</div>

<div class="container" style='margin-top: 30px;'>
    <form action="{% url 'titanic:result' %}" method="POST">
        <div >{% csrf_token %}</div>

    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Gender</h4>
        </div>
        <div class="card-body">
          
           <img src="{% static 'img/man.jpeg' %}" id='gender' class="image mb-4 rounded">
            {{ form.gender }}
        </div>
      </div>
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Class</h4>
        </div>
        <div class="card-body">
        <img src="{% static 'img/thirdclass.jpeg' %}" id='grade' class='image mb-4 rounded'>
          {{ form.grade }}
        </div>
      </div>
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Fare</h4>
        </div>
        <div class="card-body">
        <h4>US-dollar</h4>
        <img src="{% static 'img/dollar.jpg' %}" class='image-width rounded'>
        <p style="margin-bottom: 5px;">(range)</p>
        <p class="fare disNone">$25〜$512</p>
        <p class="fare disNone">$0〜$73.5</p>
        <p class="fare disNone">$0〜$69.55</p>
          {{ form.fare }}
        </div>
      </div>
    </div>
    <button id='next' type="submit" onClick='return checkSubmit();' class="btn btn-lg btn-block btn-outline-primary">判定する</button>      
    </form>
</div>
<script type='text/javascript' src="{% static 'js/images.js' %}"></script>

{% endblock content %}

 AI_Titanic/titanic/templates/titanic/result.html
{% extends 'titanic/base.html' %}
{% load static %}

{% block content %}
<div class="result">
  <div class="card-body">
    <h5 class="card-title">Result</h5>
    <h3>{{ answer |safe }}</h3>
    <hr>
    <p class="card-text">選んだ値</p>
    <h3 id=resultGen>{{ gender }}</h3>
    <h3 id='resultCla'>{{ grade }}</h3>
    <h3>${{ fare }}</h3>
    <a href="{% url 'titanic:home' %}" class="btn btn-primary">もう一度行う</a>
  </div>
</div>
<script type='text/javascript' src="{% static 'js/result.js' %}"></script>
{% endblock content %}